// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsultorioProject.Migrations
{
    [DbContext(typeof(ConsultorioContext))]
    [Migration("20230205182056_DateOnly")]
    partial class DateOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataConsulta")
                        .HasColumnType("date")
                        .HasColumnName("data_consulta");

                    b.Property<TimeSpan>("HoraFinal")
                        .HasColumnType("interval")
                        .HasColumnName("hora_final");

                    b.Property<TimeSpan>("HoraInicial")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicial");

                    b.Property<string>("PacienteCpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paciente_cpf");

                    b.HasKey("Id")
                        .HasName("pk_agendamentos");

                    b.HasIndex("PacienteCpf")
                        .HasDatabaseName("ix_agendamentos_paciente_cpf");

                    b.ToTable("agendamentos", (string)null);
                });

            modelBuilder.Entity("Paciente", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateOnly>("DataNasc")
                        .HasColumnType("date")
                        .HasColumnName("data_nasc");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Cpf")
                        .HasName("pk_pacientes");

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("Agendamento", b =>
                {
                    b.HasOne("Paciente", null)
                        .WithMany("Agendamentos")
                        .HasForeignKey("PacienteCpf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agendamentos_pacientes_paciente_cpf");
                });

            modelBuilder.Entity("Paciente", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
